trigger:
- release/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*.test.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: 'meetup/*.csproj'
    configuration: 'Release'
    versioningScheme: 'off'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'Munich.Net.Meetup.NugetTest'
    publishLocation: 'pipeline'


- task: NuGetCommand@2
  displayName: 'NuGet Push'
  inputs:
    command: push
    packagesToPush: '$(System.ArtifactsDirectory)/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'Munich-DotNet-Meetup.Github-Azure-Nuget'